-- Cria o banco se ainda não existir
CREATE DATABASE IF NOT EXISTS tarefando_kanban_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE tarefando_kanban_db;

-- ==========================
-- Tabela de usuários
-- ==========================
CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================
-- Colunas do Kanban
-- ==========================
CREATE TABLE IF NOT EXISTS KANBAN_COLUMNS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ORDER_INDEX INT NOT NULL
);

-- ==========================
-- Tarefas do Kanban
-- ==========================
CREATE TABLE IF NOT EXISTS KANBAN_TASKS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  TITLE VARCHAR(200) NOT NULL,
  DESCRIPTION TEXT,
  DUE_DATE DATE NULL,
  COLUMN_ID INT NOT NULL,
  ASSIGNED_USER_ID INT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_user
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    ON DELETE CASCADE,
  CONSTRAINT fk_tasks_column
    FOREIGN KEY (COLUMN_ID) REFERENCES KANBAN_COLUMNS(ID)
    ON DELETE RESTRICT,
  CONSTRAINT fk_tasks_assigned_user
    FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ID)
    ON DELETE SET NULL
);

-- ==========================
-- Checklist das tarefas
-- ==========================
CREATE TABLE IF NOT EXISTS KANBAN_TASK_CHECKLIST_ITEMS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TASK_ID INT NOT NULL,
  TEXT VARCHAR(255) NOT NULL,
  COMPLETED TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_checklist_task
    FOREIGN KEY (TASK_ID) REFERENCES KANBAN_TASKS(ID)
    ON DELETE CASCADE
);

-- ==========================
-- Dados iniciais: colunas padrão
-- ==========================
INSERT INTO KANBAN_COLUMNS (NAME, ORDER_INDEX)
VALUES
  ('A Fazer', 1),
  ('Em Progresso', 2),
  ('Concluído', 3)
ON DUPLICATE KEY UPDATE
  NAME = VALUES(NAME),
  ORDER_INDEX = VALUES(ORDER_INDEX);
